### PR TITLE
Add support for Waveshare ESP32-S3-Touch-LCD-4.3

### PR DESCRIPTION
**Pull request by adampr1**
Add support for Waveshare ESP32-S3-Touch-LCD-4.3 from https://github.com/HASwitchPlate/openHASP/discussions/602

### CODE REVIEW

**Comment by fvanroie** [comment]
Thanks

**Comment by manoranjan2050** [comment]
many thanks add this display to https://nightly.openhasp.com

**Comment by manoranjan2050** [comment]
any one please share pre compile bin

**Comment by adampr1** [comment]
1. Extract ZIP file end you get two bin file inside - "ws_esp32_s3_touch_lcd_4p3_full_8MB_v0.7.0-rc12_bbd96b2.bin" and "ws_esp32_s3_touch_lcd_4p3_ota_v0.7.0-rc12_bbd96b2.bin". "full" is to flash for the first time when no openhasp is installed.
2. Open web Tasmota flasher : [https://tasmota.github.io/install/](url) in CHROME or EDGE browser.
3. Select "UPLOAD factory.bin"
4. Select file "ws_esp32_s3_touch_lcd_4p3_full_8MB_v0.7.0-rc12_bbd96b2.bin" form your PC
5. Click "connect" and select serial port where you have connected  you display in BOOT mode (USB-C UART)
6. Select your device in pop-up window and then check ERASE DEVICE and then NEXT
7. Wait until finish then re-plug your usb cable and search on WiFi (with your tablet other mobile)  new openHASP device and log in.

Those both file are compiled with support for modified hardware for BackLight (GPIO6) and 1000Hz for BackLight to prevent inductor noise.
Hope its help to start with our display 
BR. Adam

[ws_esp32_s3_touch_lcd_4p3_v0.7.0-rc12.zip](https://github.com/user-attachments/files/17145789/ws_esp32_s3_touch_lcd_4p3_v0.7.0-rc12.zip)

**Comment by fvanroie** [comment]
The latest build zip files can always be downloaded from the [Actions Tab](https://github.com/HASwitchPlate/openHASP/actions/workflows/build.yaml).

**Pull request merged**
