### PR TITLE
Adding system scripts that are automatically executed when idle level is changed

### PR DESCRIPTION
**Pull request by marsman7**
Adding additional system scripts that are automatically executed when the idle level is changed.

* idle_off.cmd
* idle_short.cmd
* idle_long.cmd

In example this scripts can use to easy control the backlight or change page

* idle_off.cmd

```
backlight {"state": true, "brightness": 255}
moodlight {"state": false}
```

* idle_short.cmd

```
backlight {"state": "on", "brightness": 50}
```

* idle_long.cmd

```
backlight {"state": false, "brightness": 5}
moodlight {"state": true, "color":"green"}
```

### CODE REVIEW

**Review by fvanroie — APPROVED** [review]

**Comment by fvanroie** [comment]
Thanks. Please also update CHANGELOG.md and the docs repo.

**Comment by marsman7** [comment]
The scripts are for every user, even those who don't use HA and they work even if Wifi is disturbed. If you use HA and the scripts, you have to make sure that they do not contradict each other.

**Comment by marsman7** [comment]
I don't use HA, I don't know but you can certainly customize the HA configuration to your liking.

https://openhasp.haswitchplate.com/0.6/integrations/home-assistant/sampl_autom/

**Comment by htvekov** [comment]
> I don't use HA, I don't know but you can certainly customize the HA configuration to your liking.
> 
> https://openhasp.haswitchplate.com/0.6/integrations/home-assistant/sampl_autom/
> 
> In the link above you can see the "action" section in the HA script. Change it.

The custom component responds with a backlight state and brightness setting whenever openHASP issues an idle_xx mesage.
So changing the idle period in the openHASP device won't solve this.

It's actually an ongoing issue which is not resolved yet. Using the HA custom component it's impossible to configure whether or not you want it to respond or not on some/all idle messages.

I had to hack the component doing my openHASP proximity sensor custom code.
Another approach could be to stop openHASP from issuing some/all idle commands by setting idle time to 0

image

**Comment by htvekov** [comment]
Brightness values can be altered in HA (manually or by automation).
So it would be a challenge to ensure identical settings - One being static where the other is dynamic 😉

IMO backlight idle state/brightness should ideally be configurable and fully controlled locally on the device.
It's not a big issue for me, as I'm aware of this and know how to circumvent it.

**Comment by fvanroie** [comment]
> IMO backlight idle state/brightness should ideally be configurable and fully controlled locally on the device.

This PR implements that, and more since you can use other commends too besides brightness.

**Comment by marsman7** [comment]
The idle scripts are not only to control the backlight. In example you can use it go to a default page or control the moodlight.

**Comment by htvekov** [comment]
> > IMO backlight idle state/brightness should ideally be configurable and fully controlled locally on the device.
> 
> This PR implements that, and more since you can use other commends too besides brightness.

Yep, full local control. But on the other hand you'll then loose the possibility to dynamically control the brightness values / BL states for all three idle states.

The main issue here is that it's impossible to use the CC  and at the same time control the brightness with the new  scripts.
You simply can't turn off the idle command responses completely in the CC. And if you 'kill' the idle states from being issued from the device (setting the idle settings to zero in the device), then you'll also loose the possibility to act on the idle state change e.g. via automations in HA.
`Idle_short` brightness settings has an on/off flag and a slider value setting. But the CC doesn't respect the brightness level on/off flag (most likely a bug in the CC). Removing the flag, saving and reloading the CC will set flag again.

image

`idle_long` as well as `idle_off` has no user interface settings at all in the CC. `idle_long` will change BL state to zero and idle_off will set brightness to whatever value you've configured for the BL brightness in HA.

That's why I wrote as I did earlier. From a Home Assistant user perspective it simply would be much easier if the BL state & brightness level for the three idle states were controlled completely by openHASP core in the device. The timing config is already there. We just need the brightness/states variables internally, the ability to change these via commands and a few lines of code to change the state/levels accordingly.

If I had the skills I would definitely have made a PR for this 😉

**Comment by nagyrobi** [comment]
@dgomes

**Comment by htvekov** [comment]
> The idle scripts are not only to control the backlight. In example you can use it go to a default page or control the moodlight.

I'm aware of that 😉
It's really a great feature with these local scripts where all openHASP commands can be fired. There will most likely be _many_ use cases where this ability will come in handy 👍😎

The BL control & brightness just came to my mind as the current solution in the CC for HA users is somewhat flawed

**Pull request merged**
