### PR TITLE
Implement WireGuard VPN

### PR DESCRIPTION
**Pull request by perexg**
WireGuard VPN is ideal security mechanism for those small devices.

### CODE REVIEW

**Review by fvanroie — APPROVED** [review]
This looks very nice! Thanks.

I don't have any means to test this functionality, so I can leave this feature enabled by default in RC9 and ask some users to test it.

**Comment by TheHexaMaster** [comment]
Interresting update. Testing, but with no success - no handshake. I will do some research. 

ps - in config, i suggest to add possibility to add domain as endpoint, not strict IP (many users use dynamic DNS service).

**Comment by fvanroie** [comment]
Another user configured wireguard with ip but no handshake. @perexg  could you have a look what could be wrong?

**Comment by perexg** [comment]
Note that the device must set correct time from network at first, otherwise wireguard will not work (by design). Also note that I tried the wireguard connection only on local network, so the routing may also play a role. Also, check the status page for more information. I will try to do more tests soon.

**Pull request merged**
