### PR TITLE
[WIP/Feedback wanted] - Initial attempt to get display res/orientation info into the HA discovery payload

### PR DESCRIPTION
**Pull request by kquinsland**
An attempt to address https://github.com/HASwitchPlate/openHASP/issues/278

I do not spend a lot of time in c/c++ land. I could not figure out how to pass a pointer to an integer array and then store the values so I just pass in the integer array.

I also don't know if this should be turned into 3 functions and the functions should be added to the `haspDevice` obj.

e.g.:

```
jsonDoc[xres] = haspDevice.get_disp_x_res();
jsonDoc[yres] = haspDevice.get_disp_y_res();
jsonDoc[orient] = haspDevice.get_disp_orientation()
```

Or if i should just put the keyboard down and let the pros do it... ?

### CODE REVIEW

**Comment by fvanroie** [comment]
Thanks, that's definitely going in the right direction!
I wouldn't over-complicate things, so I made a different proposal here a7a437f48fa818d03dc8c5f325f80505f793c3a0.
The final format depends on what the Custom Component needs, so we can discuss it further in the issue #278.

**Comment by kquinsland** [comment]
> I wouldn't over-complicate things, so I made a different proposal here [a7a437f](https://github.com/HASwitchPlate/openHASP/commit/a7a437f48fa818d03dc8c5f325f80505f793c3a0).

Oh man... I wish I had spotted that `haspTft` was an object I could use :/.

I wasn't sure if it would make sense to eventually add more info in the `disp` key. Maybe there's an ESP32 chip that has support for dual displays in the future? IN the more near-term: possibly scaling / refresh-rate properties or the display inverted/colors flipped flags? 


For now, though, I think just the x/y is _almost_ sufficient... depending on where you're accessing data from. 
Only _after_ i got the PR in did i spot the x/y resolution in the device attributes.... they appear to be hard-coded, though.

https://github.com/HASwitchPlate/openHASP/blob/master/src/hasp/hasp_dispatch.cpp#L1177

That data _already_ makes it into the attributes for a given entity:

image

Rather than add the x/y res to the HA disco payload, perhaps just add the orientation via some new `tft.getRotation()` function.
As long as the function that sends the `dispatch_statusupdate()` is called every time the rotation settings are changed  then the mqtt payload that the openHASP integration parses should have the (fixed) display size and the dynamic orientation... which is everything I need for computing layouts.


If adding a new `dispOrient` field in the `dispatch_statusupdate()` function won't work, then the code [here](https://github.com/HASwitchPlate/openHASP/commit/a7a437f48fa818d03dc8c5f325f80505f793c3a0) would need that flag added + the additional openHASP work needed to parse both the statusupdate fields _and_ the disco payload to flesh out the attributes of an entity.

**Comment by fvanroie** [comment]
The format of the JSON can be anything really. I know the Custom Component does dome JSON schema validation, so whatever works...

TFT_WIDTH and TFT_HEIGHT are hardware settings from the panel _before_ any rotation. haspTft is the actual object used by the display driver. Maybe we can get away with just changing TFT_WIDTH/TFT_HEIGHT to haspTft.width()/haspTft.height() ?

**Comment by fvanroie** [comment]
If this is a usable solution, I think we can close this PR.

**Comment by kquinsland** [comment]
It looks like it will work. I will pull down the latest bin file and test the HA integration support shortly.

I think you can also remove the `disp` key creation:
https://github.com/HASwitchPlate/openHASP/commit/084f7bd6eea72802cbd58bec251fad6bf26722bf#diff-3aca8b384400a699b7e75d037b8607e345ab56754cf6e20f16d1ee757d71f7f9L1117

**Comment by kquinsland** [comment]
I pulled the latest build from the Actions tab: https://github.com/HASwitchPlate/openHASP/actions/runs/1685181958

Good news: the `tftWidth` and `tftHeight` are now dynamic / follow the screen orientation... This is enough for my needs / to address https://github.com/HASwitchPlate/openHASP/issues/278


bad news:

I can reliably crash the device by requesting the `/info` page or using the web ui to update MQTT credentials.

Clicking the `Information` button causes the crash, but directly loading the `/info` endpoint does not.

I was not able to capture the backtrace on a lanbon/l8 device because it's installed in the wall / no UART.
This is what I was able to capture via UART for the wt32-sc01 build from the same GHA run link above:

```
[1000D[0KPrompt > [1000D[9C[1000D[0K[96m[15:33:48.846][91m[65524/117636 44][92m[41[1000D[0K[96m[14:24:29.172][91m[65524/116520 43][92m[41240/41368  1][37m HTTP: Sent /info page to 192.168.127.1[0m
[1000D[0KPrompt > [1000D[9CGuru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.

Core  1 register dump:
PC      : 0x400d4833  PS      : 0x00060930  A0      : 0x800d4950  A1      : 0x3ffb24b0  
A2      : 0x00000000  A3      : 0x00000000  A4      : 0xffffff80  A5      : 0x3ffb2630  
A6      : 0x3ffe3a74  A7      : 0x3ffe3a69  A8      : 0x800d4860  A9      : 0x3ffb24a0  
A10     : 0x00000000  A11     : 0x3f420702  A12     : 0x00000008  A13     : 0x3ffe3a74  
A14     : 0x00006567  A15     : 0x65676150  SAR     : 0x00000010  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000008  LBEG    : 0x4008e9b5  LEND    : 0x4008e9d7  LCOUNT  : 0xffffffff  


Backtrace:0x400d4830:0x3ffb24b00x400d494d:0x3ffb24e0 0x400d635c:0x3ffb2520 0x400f14db:0x3ffb2620 0x401ccf01:0x3ffb2690 0x4012c2e2:0x3ffb26b0 0x4012c365:0x3ffb26d0 0x4012c3fe:0x3ffb2710 0x4012c4fe:0x3ffb2770 0x4008144e:0x3ffb27c0 0x400813d7:0x3ffb27e0 0x40081332:0x3ffb2800 0x4012fdc0:0x3ffb2820 




ELF file SHA256: 0000000000000000

Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:184
load:0x40078000,len:12352
load:0x40080400,len:2912
entry 0x400805c4

[1000D[0KPrompt > H[1000D[10C[1000D[0K[96m[14:27:33.643][91m[65524/116012 43][92m[41352/41916  2][37m HTTP: Sent /config page to 192.168.127.1[0m
[1000D[0KPrompt > H[1000D[10CGuru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.

Core  1 register dump:
PC      : 0x400ee631  PS      : 0x00060b30  A0      : 0x800eea39  A1      : 0x3ffb2440  
A2      : 0x3ffb24c0  A3      : 0x3ffc34d0  A4      : 0x00000006  A5      : 0x00000000  
A6      : 0x00000004  A7      : 0x3ffb24b0  A8      : 0x800ee963  A9      : 0x00000000  
A10     : 0x3ffb257c  A11     : 0x3ffb24b0  A12     : 0x00000004  A13     : 0x00000006  
A14     : 0x3ffb24d8  A15     : 0xff000000  SAR     : 0x00000008  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000008  LBEG    : 0x4008fd55  LEND    : 0x4008fd65  LCOUNT  : 0xfffffffe  


Backtrace:0x400ee62e:0x3ffb24400x400eea36:0x3ffb2610 0x400eeb11:0x3ffb2650 0x401ccf01:0x3ffb2690 0x4012c2e2:0x3ffb26b0 0x4012c365:0x3ffb26d0 0x4012c3fe:0x3ffb2710 0x4012c4fe:0x3ffb2770 0x4008144e:0x3ffb27c0 0x400813d7:0x3ffb27e0 0x40081332:0x3ffb2800 0x4012fdc0:0x3ffb2820 




ELF file SHA256: 0000000000000000

Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:184
load:0x40078000,len:12352
load:0x40080400,len:2912
entry 0x400805c4

[1000D[0KPrompt > [1000D[9C[1000D[0K[96m[14:29:02.316][91m[65524/116072 43][92m[41352/41912  2][37m HTTP: Sent /config page to 192.168.127.1[0m
[1000D[0KPrompt > [1000D[9CGuru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.

Core  1 register dump:
PC      : 0x400ee631  PS      : 0x00060b30  A0      : 0x800eea39  A1      : 0x3ffb2440  
A2      : 0x3ffb24c0  A3      : 0x3ffc34d0  A4      : 0x00000006  A5      : 0x00000000  
A6      : 0x00000004  A7      : 0x3ffb24b0  A8      : 0x800ee963  A9      : 0x00000000  
A10     : 0x3ffb257c  A11     : 0x3ffb24b0  A12     : 0x00000004  A13     : 0x00000006  
A14     : 0x3ffb24d8  A15     : 0xff000000  SAR     : 0x0000000c  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000008  LBEG    : 0x4008fd55  LEND    : 0x4008fd65  LCOUNT  : 0xfffffffe  


Backtrace:0x400ee62e:0x3ffb24400x400eea36:0x3ffb2610 0x400eeb11:0x3ffb2650 0x401ccf01:0x3ffb2690 0x4012c2e2:0x3ffb26b0 0x4012c365:0x3ffb26d0 0x4012c3fe:0x3ffb2710 0x4012c4fe:0x3ffb2770 0x4008144e:0x3ffb27c0 0x400813d7:0x3ffb27e0 0x40081332:0x3ffb2800 0x4012fdc0:0x3ffb2820 




ELF file SHA256: 0000000000000000

Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:184
load:0x40078000,len:12352
load:0x40080400,len:2912
entry 0x400805c4

[1000D[0KPrompt > [1000D[9C[1000D[0K[96m[14:29:20.013][91m[65524/116152 43][92m[41240/41368  1][37m HTTP: Sent /config page to 192.168.127.1[0m
[1000D[0KPrompt > [1000D[9CGuru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.

Core  1 register dump:
PC      : 0x400ee631  PS      : 0x00060b30  A0      : 0x800eea39  A1      : 0x3ffb2440  
A2      : 0x3ffb24c0  A3      : 0x3ffc34d0  A4      : 0x00000006  A5      : 0x00000000  
A6      : 0x00000004  A7      : 0x3ffb24b0  A8      : 0x800ee963  A9      : 0x00000000  
A10     : 0x3ffb257c  A11     : 0x3ffb24b0  A12     : 0x00000004  A13     : 0x00000006  
A14     : 0x3ffb24d8  A15     : 0xff000000  SAR     : 0x00000006  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000008  LBEG    : 0x4008fd55  LEND    : 0x4008fd65  LCOUNT  : 0xfffffffe  


Backtrace:0x400ee62e:0x3ffb24400x400eea36:0x3ffb2610 0x400eeb11:0x3ffb2650 0x401ccf01:0x3ffb2690 0x4012c2e2:0x3ffb26b0 0x4012c365:0x3ffb26d0 0x4012c3fe:0x3ffb2710 0x4012c4fe:0x3ffb2770 0x4008144e:0x3ffb27c0 0x400813d7:0x3ffb27e0 0x40081332:0x3ffb2800 0x4012fdc0:0x3ffb2820 




ELF file SHA256: 0000000000000000

Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:184
load:0x40078000,len:12352
load:0x40080400,len:2912
entry 0x400805c4
```

**Pull request closed without merging**
