### PR TITLE
Add W5500 SPI Ethernet 

### PR DESCRIPTION
**Pull request by bensuffolk**
Additional files and configuration to build W5500 SPI Ethernet functionality, along with a a lanbon build options ini file

### CODE REVIEW

**Comment by fvanroie** [comment]
This is great! It seems the ETH and ETHSPI classes are nearly identical, except the `begin()` method.

To reduce code duplication, I'd propose to merge the `src\sys\net\hasp_ethernet_esp32.cpp` and `src\sys\net\hasp_ethernet_spi.cpp` files and create an `HASP_ETHERNET` flag to define either the `ETH` or `ETHSPI` class.

I can't test it but I've updated `master` and it compiles fine. Can you give it a go?
I need to get some W5500 modules to properly test...

**Comment by nagyrobi** [comment]
> I need to get some W5500 modules to properly test...

Yeah me too. Any advice which ones worth best?

**Comment by bensuffolk** [comment]
Ok, Have tested, network is ok, I can access the web and telnet, but MQTT won't connect. I shall have to investigate and see if I can find out why.

**Comment by bensuffolk** [comment]
I have created a new [pull request #345](https://github.com/HASwitchPlate/openHASP/pull/345) to fix MQTT on Ethernet

**Pull request merged**
